name: Commits

on:
  pull_request:
    type: [opened, reopened, edited]

jobs:

  commits:
    name: Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Check commits
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
